import FooterCommon from './common/footer'
import CopyCommon from './common/copy'
import HeaderCommon from './common/header'
import InfoTextCommon from './common/infoText'

import {
  AuthorCard,
  AutoScaleImage,
  Body,
  Page,
  Paragraph,
  Title,
  AuthorCardWrapper,
  Span,
  // ExternalLink,
  NextPrev,
  // UnorderedList,
  // ListItem
} from '../components'
// import ExternalLinkComponent from '../components/externalLink';
// import { ExternalLink } from './../components/externalLink';

export default {
  name: 'generateReactCode',
  url: 'generate-react-code',
  content: Page(
    HeaderCommon,
    Body(
      AuthorCardWrapper([
        AuthorCard({
          src: '/static/blog/paul.jpg',
          name: 'Paul Brie',
          twitterHandle: '@aelythe',
          twitterLink: 'https://twitter.com/@aelythe',
        }),
        Span('Posted on February 25, 2019'),
      ]),
      Title('Generate React Code'),

      Paragraph(
        `To generate code we only need 2 things: a source (under the form of a UIDL representation), and generator. To that extent, we need to install our ‘@teleporthq/teleport-code-generators’, to instantiate them and to pass the source as a parameter.`
      ),

      AutoScaleImage({
        src: '/static/blog/code3.png',
        alt: 'Snippet of code.',
      }),

      Paragraph(`The output generated by the above example will look like this:`),

      AutoScaleImage({
        src: '/static/blog/code4.png',
        alt: 'Snippet of code.',
      }),

      NextPrev('< Setup', 'setup', 'Adding styles >', 'adding-styles')
    ),
    InfoTextCommon,
    FooterCommon,
    CopyCommon
  ),
}
